name: 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - statsmodels
  - pymc
  - arviz
  - pytensor
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
